// 층, 호실, 교시, 요일 순서로 구조화된 강의 유무 데이터 객체 (true: 수업 있음, false: 없음)
const timeTable = {
    "3": {
    // 3층 강의실: 301, 302, 303, 304, 305, 306, 307, 308, 310
    301: {
      1: [false, false, false, false],
      2: [true, true, true, false],
      3: [true, true, true, false],
      4: [true, false, false, false],
      5: [true, true, true, false],
      6: [true, true, true, false],
      7: [true, false, true, false],
      8: [true, false, true, false],
      9: [false, false, false, false], 

    },
    302: {
      1: [true, false, false, true],
      2: [true, true, false, true],
      3: [true, true, true, true],
      4: [false, true, true, true],
      5: [false, true, true, true],
      6: [false, true, false, true],
      7: [false, false, true, false],
      8: [false, false, true, false],
      9: [false, false, false, false], 
    },
    303: {
      1: [false, false, false, true],
      2: [false, true, false, true],
      3: [false, true, false, true],
      4: [true, false, false, false],
      5: [true, true, true, true],
      6: [true, true, true, true],
      7: [true, false, false, false],
      8: [true, false, true, false],
      9: [true, false, false, false], 
    },
    304: {
      1: [false, false, true, false],
      2: [false, false, true, false],
      3: [false, false, true, false],
      4: [false, false, true, false],
      5: [false, false, true, false],
      6: [false, false, true, false],
      7: [false, false, true, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    305: {
      1: [false, true, true, true],
      2: [false, true, true, true],
      3: [false, true, true, false],
      4: [false, true, false, true],
      5: [false, true, true, true],
      6: [false, true, true, true],
      7: [false, false, true, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    306: {
      1: [false, false, false, false],
      2: [true, false, false, false],
      3: [true, false, false, false],
      4: [true, false, false, true],
      5: [true, false, true, true],
      6: [false, false, true, true],
      7: [false, false, true, false],
      8: [false, false, true, false],
      9: [false, false, false, false],
    },
    307: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    308: {
      1: [false, false, false, false],
      2: [false, true, true, false],
      3: [false, false, true, false],
      4: [false, false, false, false],
      5: [true, true, false, false],
      6: [false, true, false, false],
      7: [false, false, true, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    310: {
      1: [false, false, true, false],
      2: [false, true, true, true],
      3: [false, true, true, true],
      4: [false, true, true, false],
      5: [false, false, true, true],
      6: [false, true, true, false],
      7: [false, true, true, false],
      8: [false, true, false, false],
      9: [false, true, false, false],
    },
  },
  "4": {
    // 4층 강의실: 401, 402, 403, 404, 405, 406, 407, 408, 410, 411
    401: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, true, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    402: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    403: {
      1: [false, true, false, true],
      2: [false, true, false, true],
      3: [true, true, false, true],
      4: [true, true, false, true],
      5: [false, false, true, false],
      6: [false, false, true, true],
      7: [true, false, false, false],
      8: [true, false, false, false],
      9: [false, false, false, false],
    },
    404: {
      1: [false, false, false, false],
      2: [false, false, true, false],
      3: [true, true, true, false],
      4: [true, true, true, false],
      5: [true, false, true, false],
      6: [true, false, true, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    405: {
      1: [false, false, false, false],
      2: [false, false, true, false],
      3: [false, false, true, false],
      4: [false, false, false, false],
      5: [false, false, true, false],
      6: [false, true, true, false],
      7: [false, true, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    406: {
      1: [false, false, false, true],
      2: [false, true, false, true],
      3: [true, true, true, true],
      4: [true, false, true, true],
      5: [true, false, true, false],
      6: [true, false, true, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    407: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    408: {
      1: [false, true, false, false],
      2: [false, true, false, false],
      3: [false, true, true, false],
      4: [false, true, true, false],
      5: [true, false, true, false],
      6: [true, false, true, false],
      7: [true, false, false, false],
      8: [true, false, false, false],
      9: [false, false, false, false],
    },
    410: {
      1: [false, false, false, false],
      2: [false, false, false, true],
      3: [false, true, true, true],
      4: [false, true, true, false],
      5: [true, false, true, true],
      6: [true, true, true, true],
      7: [true, true, false, true],
      8: [true, false, false, true],
      9: [false, false, false, false],
    },
    411: {
      1: [false, false, true, false],
      2: [false, false, true, false],
      3: [false, false, true, false],
      4: [false, false, true, false],
      5: [false, false, true, false],
      6: [false, false, true, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
  },
  "5": {
    // 5층 강의실: 501, 502, 503, 504, 505, 506, 508, 509
    501: {
      1: [false, false, false, false],
      2: [false, false, true, false],
      3: [false, false, true, false],
      4: [false, false, true, false],
      5: [false, false, true, false],
      6: [false, false, true, false],
      7: [false, false, true, false],
      8: [false, false, false, false],
      9: [false, false, false, false],    },
    502: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],
    },
    503: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],    },
    504: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],    },
    506: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],    },
    508: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],    },
    509: {
      1: [false, false, false, false],
      2: [false, false, false, false],
      3: [false, false, false, false],
      4: [false, false, false, false],
      5: [false, false, false, false],
      6: [false, false, false, false],
      7: [false, false, false, false],
      8: [false, false, false, false],
      9: [false, false, false, false],    },
  },
};

// 층별 시설 안내 및 특징 설명 데이터
const floorData = {
  "3F": {
    description: [
      "교수 연구 공간 + 강의실 9개 (301~306, 308, 310)",
      "휴게실 O, 정수기 O(화장실 옆)", " 308 강당형 / 나머지 교실형",
      "연결 계단(목양) 308호 옆, 강의실 앞 의자: 308, 306",
      "인대관 교수실 309, 강사휴게실 311",
    ],
  },
  "4F": {
    description: [
      "대형 강의 공간, 강의실 10개 (401~406, 408, 410, 411)",
      "중앙 계단 O, 정수기 O", "408 강당형 / 나머지 교실형",
      "연결 계단(목양) O, 교수연구실 409",
    ],
  },
  "5F": {
    description: [
      "행정 및 사무 공간 + 강의실 7개 (501~504, 506, 508, 509)",
      "중앙 계단 왼쪽, 정수기 O", "506 강당형 / 508 스터디 / 나머지 교실형",
      "연결 계단(목양) O, 강의실 앞 의자 504", "교수연구실 507",
    ],
  },
};